/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ejemplos;

import java.awt.CardLayout;
import java.awt.Event;

/**
 *
 * @author node
 */
public class EjemploCardLayout extends javax.swing.JFrame {

    /**
     * Creates new form EjemploCardLayout
     */
    public EjemploCardLayout() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radio = new javax.swing.ButtonGroup();
        SelecionPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        ResultadoPanel = new javax.swing.JPanel();
        botones = new javax.swing.JPanel();
        combos = new javax.swing.JPanel();
        check = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SelecionPanel.setBackground(new java.awt.Color(0, 153, 153));
        SelecionPanel.setPreferredSize(new java.awt.Dimension(200, 300));
        SelecionPanel.setLayout(new javax.swing.BoxLayout(SelecionPanel, javax.swing.BoxLayout.Y_AXIS));

        jLabel1.setText("Escoje Panel:");
        SelecionPanel.add(jLabel1);

        radio.add(jRadioButton1);
        jRadioButton1.setText("botones");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        SelecionPanel.add(jRadioButton1);

        radio.add(jRadioButton2);
        jRadioButton2.setText("combos");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        SelecionPanel.add(jRadioButton2);

        radio.add(jRadioButton3);
        jRadioButton3.setText("checkboxs");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        SelecionPanel.add(jRadioButton3);

        getContentPane().add(SelecionPanel, java.awt.BorderLayout.LINE_START);

        ResultadoPanel.setBackground(new java.awt.Color(153, 0, 153));
        ResultadoPanel.setLayout(new java.awt.CardLayout());

        botones.setBackground(new java.awt.Color(255, 204, 255));
        botones.setAutoscrolls(true);

        javax.swing.GroupLayout botonesLayout = new javax.swing.GroupLayout(botones);
        botones.setLayout(botonesLayout);
        botonesLayout.setHorizontalGroup(
            botonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 397, Short.MAX_VALUE)
        );
        botonesLayout.setVerticalGroup(
            botonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 385, Short.MAX_VALUE)
        );

        ResultadoPanel.add(botones, "BOTONES");

        combos.setBackground(new java.awt.Color(153, 153, 255));

        javax.swing.GroupLayout combosLayout = new javax.swing.GroupLayout(combos);
        combos.setLayout(combosLayout);
        combosLayout.setHorizontalGroup(
            combosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 397, Short.MAX_VALUE)
        );
        combosLayout.setVerticalGroup(
            combosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 385, Short.MAX_VALUE)
        );

        ResultadoPanel.add(combos, "COMBOS");

        check.setBackground(new java.awt.Color(255, 204, 153));

        javax.swing.GroupLayout checkLayout = new javax.swing.GroupLayout(check);
        check.setLayout(checkLayout);
        checkLayout.setHorizontalGroup(
            checkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 397, Short.MAX_VALUE)
        );
        checkLayout.setVerticalGroup(
            checkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 385, Short.MAX_VALUE)
        );

        ResultadoPanel.add(check, "CHECK");

        getContentPane().add(ResultadoPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        CardLayout paneis = (CardLayout) this.ResultadoPanel.getLayout();
        paneis.show(this.ResultadoPanel, "BOTONES");
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        CardLayout paneis = (CardLayout) this.ResultadoPanel.getLayout();
        paneis.show(this.ResultadoPanel, "CHECK");

    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
        CardLayout paneis = (CardLayout) this.ResultadoPanel.getLayout();
        paneis.show(this.ResultadoPanel, "COMBOS");
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EjemploCardLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EjemploCardLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EjemploCardLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EjemploCardLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EjemploCardLayout().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ResultadoPanel;
    private javax.swing.JPanel SelecionPanel;
    private javax.swing.JPanel botones;
    private javax.swing.JPanel check;
    private javax.swing.JPanel combos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.ButtonGroup radio;
    // End of variables declaration//GEN-END:variables
}
