package Ejemplos;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author node
 */
public class FrmBorde extends javax.swing.JFrame {

    /**
     * Creates new form FrmBorde
     */
    public FrmBorde() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PaneEste = new javax.swing.JPanel();
        PanelCentral = new javax.swing.JPanel();
        nombre = new javax.swing.JLabel();
        amarillo = new javax.swing.JTextField();
        PanelNorte = new javax.swing.JPanel();
        datosCubrir = new javax.swing.JLabel();
        PanelOeste = new javax.swing.JPanel();
        aceptar = new javax.swing.JButton();
        PanelSur = new javax.swing.JPanel();
        disenoExcelente = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PaneEste.setBackground(new java.awt.Color(0, 255, 0));

        javax.swing.GroupLayout PaneEsteLayout = new javax.swing.GroupLayout(PaneEste);
        PaneEste.setLayout(PaneEsteLayout);
        PaneEsteLayout.setHorizontalGroup(
            PaneEsteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        PaneEsteLayout.setVerticalGroup(
            PaneEsteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(PaneEste, java.awt.BorderLayout.CENTER);

        PanelCentral.setBackground(java.awt.Color.green);

        nombre.setText("Nombre");
        PanelCentral.add(nombre);

        amarillo.setBackground(java.awt.Color.yellow);
        amarillo.setForeground(java.awt.Color.yellow);
        amarillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amarilloActionPerformed(evt);
            }
        });
        PanelCentral.add(amarillo);

        getContentPane().add(PanelCentral, java.awt.BorderLayout.CENTER);

        PanelNorte.setBackground(new java.awt.Color(0, 255, 255));

        datosCubrir.setText("Datos a cubrir");
        PanelNorte.add(datosCubrir);

        getContentPane().add(PanelNorte, java.awt.BorderLayout.PAGE_START);

        PanelOeste.setBackground(java.awt.Color.blue);

        aceptar.setText("Aceptar");
        PanelOeste.add(aceptar);

        getContentPane().add(PanelOeste, java.awt.BorderLayout.LINE_START);

        PanelSur.setBackground(new java.awt.Color(255, 153, 153));

        disenoExcelente.setText("Diseño excelente");
        disenoExcelente.setToolTipText("");
        PanelSur.add(disenoExcelente);

        getContentPane().add(PanelSur, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void amarilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amarilloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amarilloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmBorde.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmBorde.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmBorde.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmBorde.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmBorde().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PaneEste;
    private javax.swing.JPanel PanelCentral;
    private javax.swing.JPanel PanelNorte;
    private javax.swing.JPanel PanelOeste;
    private javax.swing.JPanel PanelSur;
    private javax.swing.JButton aceptar;
    private javax.swing.JTextField amarillo;
    private javax.swing.JLabel datosCubrir;
    private javax.swing.JLabel disenoExcelente;
    private javax.swing.JLabel nombre;
    // End of variables declaration//GEN-END:variables
}
